services :

  web:
    build: ./requirements/nginx
    image: nginx
    container_name: mynginx
    volumes:
    - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - wordpress_data:/var/www/html
    ports:
    - "443:443"
    env_file : .env
    depends_on:
    - wordpress
    networks:
      - my_network
    restart: unless-stopped
  
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: mywordpress
    depends_on:
    - mariadb
    env_file : .env
    secrets:
      - db_password
      - credentials
    networks:
    - my_network
    volumes:
    - ./requirements/wordpress/conf/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    - wordpress_data:/var/www/html
    restart: unless-stopped

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mymariadb
    env_file : .env
    secrets:
      - db_root_password
      - db_password
    networks:
    - my_network
    volumes:
    - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dockerfolder/data/mariadb'
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/dockerfolder/data/wordpress'

secrets:
  db_root_password:
    file: ../secrets/db_root_password
  db_password:
    file: ../secrets/db_password
  credentials:
    file: ../secrets/credentials.txt

networks:
  my_network:
    driver: bridge
